### ISSUE TITLE
merge upstream NewHope Simple HFS PQ KEM

### ISSUE THREAD

**Issue by david415** [katzenpost/noise#7]
we really should stop maintaining this noise fork and instead get Yawning's changes merged upstream.

1. currently the blocker is that flynn has a silly policy of requiring changes to be gpg signed with a legal name. but maybe we can get them to change their policy?

2. the noise protocol HFS extensions are not yet finalized and perhaps flynn will not want to merge our fork since it will likely not comply with whatever upsteam noise HFS extension is finally agreed upon.

**Comment by Yawning** [comment]
The bigger blocker is that Yawning's changes are under a strong copyleft license.
