### ISSUE TITLE
Update Kyber to non-broken version

### ISSUE THREAD

**Issue by david415** [katzenpost/noise#9]
Currently either this Kyber implementation or the liboqs Kyber is broken. Or perhaps both are broken. I say this because they are not compatible. For more information about this incompatibility please see: https://github.com/cloudflare/circl/issues/213 AND https://github.com/open-quantum-safe/liboqs/issues/909

Once these incompatibility issues are resolved we may have to update our go-modules to use the latest version of Cloudflare's Circl library's Kyber implementation.

**Comment by thomwiggers** [comment]
The `oqs` crate that's currently on `crates.io` uses Kyber Round 2. Unfortunately the Rust crate is waiting for liboqs to do a release before I want to bump the version.

**Comment by david415** [comment]
I now see this as a non-issue since we can simply use the main git branch of the oqs crate.
